##########
# pihole #
##########
# to run use:
# sudo docker-compose up -d
# info:
# http://tonylawrence.com/posts/unix/synology/free-your-synology-ports/

# using version 2 the only version that seems to support specifying MAC and IP addresses
version: '2'

networks:
  network:
    driver: macvlan        # dockers network driver named macvlan
    driver_opts:
      parent: eth0          # host network interface
    ipam:
      config:
        - subnet: 192.168.1.0/24            # <-- Update
          gateway: 192.168.1.1              # <-- Update
          ip_range: 192.168.1.192/28        # <-- Update

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    volumes:
      - './data:/etc/pihole'
      - './hosts.txt:/etc/hosts'
#      - './var:/var'
    hostname: pihole
    #cap_add: (pihole DHCP needs NET_ADMIN)
    #  - NET_ADMIN
    #domainname: example.com          # <-- Update
    mac_address: d0:ca:ab:cd:ef:02
    networks:
      network:
        ipv4_address: 192.168.1.200   # <-- Update
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
#    extra_hosts:                   # moved to host file
#      - 'mamba:192.168.1.3'
#      - ...
    environment:
      TZ: Europe/Zurich
      ServerIP: 192.168.1.200   # <-- Update (match ipv4_address)
      #VIRTUAL_HOST: pihole.example.com      # <-- Update (match hostname + domainname)
      WEBPASSWORD: ''           # <-- Add password (if required) (disable for random)
    restart: unless-stopped
    